CREATE DATABASE FunDatabase;
GO

USE FunDatabase;
GO

CREATE SCHEMA infoData;
GO

CREATE TABLE infoData.Countries (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(40) NOT NULL UNIQUE,
	Capital VARCHAR(40) NOT NULL,
	SquareSize INT,
	PeopleCount INT
);

CREATE TABLE infoData.Sights (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	Name VARCHAR(70) NOT NULL,
	Description VARCHAR(500) NOT NULL,
);

CREATE TABLE infoData.Organizations (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	Name VARCHAR(70) NOT NULL,
	CreationDate VARCHAR(50) NOT NULL,
	MainWorkingDirection VARCHAR(70) NOT NULL
);

CREATE TABLE infoData.Sites (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	Name VARCHAR(70) NOT NULL,
	CreationDate VARCHAR(70) NOT NULL,
	Category VARCHAR(150) NOT NULL
);

CREATE TABLE infoData.Streamers (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	Name VARCHAR(70) NOT NULL,
	ContentType VARCHAR(50) NOT NULL,
	BirthDate VARCHAR(50) NOT NULL, 
	Gender VARCHAR(20) NOT NULL
);

CREATE TABLE infoData.Brands (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	OrganizationID INT REFERENCES infoData.Organizations(ID),
	Name VARCHAR(70) NOT NULL,
	CreationDate VARCHAR(50) NOT NULL
);

CREATE TABLE infoData.Cities (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	Name VARCHAR(70) NOT NULL,
	IsCapital VARCHAR(5) NOT NULL, 
	PeopleCount INT NOT NULL,
	FamousFor VARCHAR(500) NOT NULL
);

CREATE TABLE infoData.Languages (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(70) NOT NULL,
	PeopleSpeaking INT NOT NULL, 
	Difficulty VARCHAR(20) NOT NULL,
	Letters INT NOT NULL,
);

CREATE TABLE infoData.Religion (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(70) NOT NULL UNIQUE,
	WorldNumberPosition INT NOT NULL, 
	FoundationDate VARCHAR(100) NOT NULL,
	PeopleCount BIGINT NOT NULL,
);

CREATE TABLE infoData.Holidays (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	Name VARCHAR(70) NOT NULL,
	FoundationDate VARCHAR(50) NOT NULL,
	Description VARCHAR(500) NOT NULL,
);

CREATE TABLE infoData.Bands (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	Name VARCHAR(70) NOT NULL,
	FoundationDate VARCHAR(50) NOT NULL,
	BandType VARCHAR(50) NOT NULL,
	PeopleInBand INT NOT NULL,
);

CREATE TABLE infoData.Artists (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	BandID INT REFERENCES infoData.Bands(ID),
	Name VARCHAR(70) NOT NULL,
	BirthDate VARCHAR(50) NOT NULL,
	Gender VARCHAR(10) NOT NULL
);

CREATE TABLE infoData.Games (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	OrganizationID INT REFERENCES infoData.Organizations(ID),
	Name VARCHAR(70) NOT NULL,
	CreationDate VARCHAR(50) NOT NULL,
	Description VARCHAR(1000) NOT NULL
);

CREATE TABLE infoData.Economics (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	CountryName VARCHAR(50) NOT NULL,
	VVP VARCHAR(70) NOT NULL
);

CREATE TABLE infoData.Facts (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	FactName VARCHAR(50) NOT NULL,
	FactDescription VARCHAR(500) NOT NULL
);

CREATE TABLE infoData.Cinema (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	CinemaType VARCHAR(50) NOT NULL,
	CreationDate VARCHAR(50) NOT NULL,
	Description VARCHAR(500) NOT NULL
);

CREATE TABLE infoData.Money (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CountryID INT REFERENCES infoData.Countries(ID),
	Name VARCHAR(50) NOT NULL,
	MoneyType VARCHAR(50) NOT NULL
);

CREATE TABLE infoData.Music (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Direction VARCHAR(50) NOT NULL,
	BandName VARCHAR(50) NOT NULL
);

CREATE TABLE infoData.Legends (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	LegendName VARCHAR(50) NOT NULL,
	Description VARCHAR(500) NOT NULL,
	OnRealEvents VARCHAR(10) NOT NULL
);

CREATE TABLE infoData.Cybersport (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Game VARCHAR(50) NOT NULL,
	HasBigChampionships VARCHAR(50) NOT NULL,
	AverageNumberOfViewers VARCHAR(500) NOT NULL,
	FamousTeams VARCHAR(70) NOT NULL,
);

CREATE TABLE infoData.UserInfo (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Login VARBINARY(800) NOT NULL,
	Password VARBINARY(800) NOT NULL
);

CREATE TABLE infoData.History (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	ActionDate DATE NOT NULL,
	ActionType VARCHAR(30) NOT NULL,
	ActionDescription VARCHAR(800)
);

ALTER TABLE infoData.Sights  WITH CHECK ADD CONSTRAINT FK_Sights_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Organizations  WITH CHECK ADD CONSTRAINT FK_Organizations_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Brands  WITH CHECK ADD CONSTRAINT FK_Brands_Organizations FOREIGN KEY(OrganizationID)
REFERENCES infoData.Organizations(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Sites  WITH CHECK ADD CONSTRAINT FK_Sites_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Streamers  WITH CHECK ADD CONSTRAINT FK_Streamers_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Cities  WITH CHECK ADD CONSTRAINT FK_Cities_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Holidays  WITH CHECK ADD CONSTRAINT FK_Holidays_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Bands  WITH CHECK ADD CONSTRAINT FK_Bands_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Artists  WITH CHECK ADD CONSTRAINT FK_Artists_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO

ALTER TABLE infoData.Artists  WITH CHECK ADD CONSTRAINT FK_Artists_Bands FOREIGN KEY(BandID)
REFERENCES infoData.Bands(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Games  WITH CHECK ADD CONSTRAINT FK_Games_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Games  WITH CHECK ADD CONSTRAINT FK_Games_Organizations FOREIGN KEY(OrganizationID)
REFERENCES infoData.Organizations(ID)
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO

ALTER TABLE infoData.Economics  WITH CHECK ADD CONSTRAINT FK_Economics_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Cinema  WITH CHECK ADD CONSTRAINT FK_Cinema_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE infoData.Money  WITH CHECK ADD CONSTRAINT FK_Money_Countries FOREIGN KEY(CountryID)
REFERENCES infoData.Countries(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO